name: Deploy

on:
  release:
    types: [prereleased]

env:
  REGION: sa-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:14

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_SOCKET_HOST: https://naval-combat-notification.evshosting.net
          envkey_REACT_APP_SOCKET_PORT: 443
          envkey_REACT_APP_SERVICE_HOST: https://stg.evshosting.net/naval-combat

      - name: Install dependencies 
        run: yarn

      - name: Build app
        run: yarn build

      - name: Deploy app
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: evs-react
          source_dir: "build"