name: Deploy

on:
  release:
    types: [prereleased]

env:
  REGION: sa-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:14

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install dependencies 
        run: yarn

      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_SOCKET_HOST: https://stg.evshosting.net/naval-combat
          envkey_REACT_APP_SOCKET_PORT: 443
          envkey_REACT_APP_SERVICE_HOST: https://naval-combat-notification.evshosting.net

      - name: Build app
        run: yarn build

      - name: Deploy app
        run: aws s3 cp --recursive ./build/ s3://evs-react/